// Maps team code (FIFA 3-letter) to ISO 3166-1 alpha-2 country code for flag CDN.
// Covers all 48 confirmed/likely 2026 World Cup participants + common placeholders.

const CODE_TO_ISO: Record<string, string> = {
  // Hosts
  USA: "us",
  CAN: "ca",
  MEX: "mx",
  // UEFA
  ENG: "gb-eng",
  SCO: "gb-sct",
  WAL: "gb-wls",
  NIR: "gb-nir",
  FRA: "fr",
  GER: "de",
  ESP: "es",
  POR: "pt",
  ITA: "it",
  NED: "nl",
  BEL: "be",
  CRO: "hr",
  SUI: "ch",
  AUT: "at",
  DEN: "dk",
  SWE: "se",
  NOR: "no",
  POL: "pl",
  UKR: "ua",
  TUR: "tr",
  CZE: "cz",
  SRB: "rs",
  HUN: "hu",
  ROU: "ro",
  GRE: "gr",
  IRL: "ie",
  SVN: "si",
  SVK: "sk",
  ALB: "al",
  BIH: "ba",
  // CONMEBOL
  BRA: "br",
  ARG: "ar",
  URU: "uy",
  COL: "co",
  CHI: "cl",
  PER: "pe",
  ECU: "ec",
  PAR: "py",
  VEN: "ve",
  BOL: "bo",
  // CONCACAF
  CRC: "cr",
  PAN: "pa",
  HON: "hn",
  JAM: "jm",
  HAI: "ht",
  SLV: "sv",
  GUA: "gt",
  CUB: "cu",
  CUW: "cw",
  TRI: "tt",
  // CAF
  MAR: "ma",
  EGY: "eg",
  TUN: "tn",
  ALG: "dz",
  SEN: "sn",
  NGA: "ng",
  CIV: "ci",
  CMR: "cm",
  GHA: "gh",
  MLI: "ml",
  RSA: "za",
  COD: "cd",
  CGO: "cg",
  ANG: "ao",
  BFA: "bf",
  CPV: "cv",
  GAB: "ga",
  GUI: "gn",
  GNB: "gw",
  KEN: "ke",
  UGA: "ug",
  ZAM: "zm",
  ZIM: "zw",
  // AFC
  JPN: "jp",
  KOR: "kr",
  AUS: "au",
  IRN: "ir",
  KSA: "sa",
  QAT: "qa",
  UAE: "ae",
  IRQ: "iq",
  JOR: "jo",
  UZB: "uz",
  CHN: "cn",
  THA: "th",
  IDN: "id",
  VIE: "vn",
  MAS: "my",
  // OFC
  NZL: "nz",
  FIJ: "fj",
  SOL: "sb",
  // Other
  ISR: "il",
  LBN: "lb",
  PLE: "ps",
};

export function flagUrl(code: string | undefined | null, size: 40 | 80 = 40): string | null {
  if (!code) return null;
  const iso = CODE_TO_ISO[code.toUpperCase()];
  if (!iso) return null;
  return `https://flagcdn.com/w${size}/${iso}.png`;
}
